In [ ]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# AND gate 입력과 출력
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 0, 0, 1])  # AND gate 결과
#y = np.array([0, 1, 1, 1])
# 모델 생성 및 학습
model = LogisticRegression(# z = w0x0+w1x1+b, y = sigmoid(z) = 1/(1+e-z)
    C=1e6,                # 규제 거의 없음
    max_iter=10000,       # 충분히 수렴
    solver='liblinear',   # 작은 데이터에서 안정적
    class_weight='balanced'   # 원하면 켜보세요) 
)
model.fit(X, y)

# 예측
predictions = model.predict(X)
print("입력 X:")
print(X)
print("예측 결과:")
print(predictions)

# 실제 값과 비교
print("정답과 일치 여부:", predictions == y)


입력 X:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
예측 결과:
[0 1 1 1]
정답과 일치 여부: [ True  True  True  True]


In [ ]:
# AI 겨울 1차 
from sklearn.linear_model import LogisticRegression
import numpy as np

# XOR gate 입력과 출력
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 1, 1, 0])  # XOR 결과

# 모델 생성 및 학습
model = LogisticRegression(
    # z = w0x0+w1x1+b, y = sigmoid(z) = 1/(1+e-z)
    C=1e6,                # 규제 거의 없음
    max_iter=10000,       # 충분히 수렴
    solver='liblinear',   # 작은 데이터에서 안정적
    class_weight='balanced'   # 원하면 켜보세요) 
)
model.fit(X, y)

# 예측
predictions = model.predict(X)
print("입력 X:")
print(X)
print("예측 결과:")
print(predictions)

# 실제 값과 비교
print("정답과 일치 여부:", predictions == y)


입력 X:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
예측 결과:
[0 0 0 0]
정답과 일치 여부: [ True False False  True]


PolynomialFeatures(degree=2)는 입력 특성 x0, x1로 부터 

모든 조합의 항을 차수 ≤ 2 범위에서 자동 생성

특성 이름: ['1' 'x0' 'x1' 'x0^2' 'x0 x1' 'x1^2']

[[1. 0. 0. 0. 0. 0.]

 [1. 0. 1. 0. 0. 1.]

 [1. 1. 0. 1. 0. 0.]
 
 [1. 1. 1. 1. 1. 1.]]


In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
import numpy as np

# XOR 데이터
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 1, 1, 0])

# 다항 특성 추가 + 로지스틱 회귀 파이프라인
model = make_pipeline(PolynomialFeatures(degree=2), LogisticRegression(
    # z = w0x0+w1x1+b, y = sigmoid(z) = 1/(1+e-z)
    C=1e6,                # 규제 거의 없음
    max_iter=10000,       # 충분히 수렴
    solver='liblinear',   # 작은 데이터에서 안정적
    class_weight='balanced'   # 원하면 켜보세요) 
))
model.fit(X, y)

# 예측
predictions = model.predict(X)
print("예측 결과:", predictions)
print("정답과 일치 여부:", predictions == y)


예측 결과: [0 1 1 0]
정답과 일치 여부: [ True  True  True  True]


In [ ]:
from sklearn.neural_network import MLPClassifier
import numpy as np

# XOR gate 입력과 출력
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 1, 1, 0])  # XOR 결과

# MLP 모델 생성: 은닉층 1개 (노드 2개), 활성화 함수 'relu'
mlp = MLPClassifier(hidden_layer_sizes=(2,), activation='tanh',
                    solver='lbfgs', max_iter=10000, alpha=1e-6,random_state=0)

# 모델 학습
mlp.fit(X, y)

# 예측
predictions = mlp.predict(X)
print("예측 결과:", predictions)
print("정답과 일치 여부:", predictions == y)


예측 결과: [1 1 1 0]
정답과 일치 여부: [False  True  True  True]


In [ ]:
#Multi-Layer Perceptron Classifier

from sklearn.neural_network import MLPClassifier
import numpy as np

# XOR 입력과 출력
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 1, 1, 0])  # XOR 결과

# MLP 모델: 은닉층 2개 (4, 4), 활성화 tanh
mlp = MLPClassifier(hidden_layer_sizes=(4, 4),
                    activation='tanh',
                    solver='adam',
                    max_iter=5000,
                    random_state=42)

# 학습
mlp.fit(X, y)

# 예측
predictions = mlp.predict(X)
print("예측 결과:", predictions)
print("정답과 일치 여부:", predictions == y)


예측 결과: [0 1 1 0]
정답과 일치 여부: [ True  True  True  True]


In [22]:
from sklearn.neural_network import MLPClassifier
import numpy as np

# XOR 입력과 출력
X = np.array([[0, 0, 0],
              [0, 1, 0],
              [1, 0, 0],
              [0, 0, 1],
              [0, 1, 1],
              [1, 1, 0],
              [1, 0, 1],
              [1, 1, 1]])
y = np.array([0, 1, 1, 1, 0,0,0,1])  # XOR 결과

# MLP 모델: 은닉층 2개 (4, 4), 활성화 tanh
mlp = MLPClassifier(hidden_layer_sizes=(4, 4),
                    activation='tanh',
                    solver='adam',
                    max_iter=5000,
                    random_state=42)

# 학습
mlp.fit(X, y)

# 예측
predictions = mlp.predict(X)
print("예측 결과:", predictions)
print("정답과 일치 여부:", predictions == y)

예측 결과: [0 1 1 1 0 0 0 1]
정답과 일치 여부: [ True  True  True  True  True  True  True  True]


1차 AI 겨울(1970년대 초반) → 대표적인 계기 중 하나가 퍼셉트론이 XOR 문제를 풀 수 없다는 한계가 널리 알려진 것

- (1969년 Minsky & Papert의 『Perceptrons』에서 단층 퍼셉트론의 한계 지적)


2차 AI 겨울(1980년대 후반~1990년대 중반) → 주된 원인은 **전문가 시스템(Expert Systems)**의 실패

- 1980년대 초~중반, 전문가 시스템이 상업적으로 대규모 투자와 붐을 일으킴 (예: XCON, MYCIN 등)

  > 유지보수 비용 급증, 지식베이스 확장의 어려움, 기대 대비 성능 저조

- 동시에 일본의 5세대 컴퓨터 프로젝트도 실패로 끝나면서 신뢰 하락

- 미국 DARPA(DoD Defense Advanced Research Projects Agency)도 AI 연구 자금 대폭 삭감
  > 1990년대 초중반까지 AI 분야 전반에 투자 위축과 관심 급감